name = "vid-playlist-man"
main = "build/index.js"
compatibility_date = "2025-10-31"

[build]
command = "cargo install -q worker-build && worker-build --release"

[placement]
mode = "smart"

[dev]
ip = "0.0.0.0"
port = 8800
local_protocol = "http"

[triggers]
crons = ["0 * * * *"] # “At every 5th minute.” -crontab.guru

[[kv_namespaces]]
binding = "VID_PLAYLIST_MANAGER_KV"
id = "ba00cb939ce14c87bfd9335278095ab0"
preview_id = "53e56989bf9548e38b0a7d82f3c78ca6"
remote = true

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true
